### ISSUE TITLE
Saving problem....

### ISSUE THREAD

**Issue by stalkeriy2010** [Agneese-Saini/SA-MP-Files#10]
hi gammix its me again :P 
so i found a link but it seems to be redrex BUILD 4 however i tested it and it was perfect like the others but i found a problem that i thought that it will be fixed in this build but it wasnt, well the problem is saving i cant save skins please help !

PS 2: im a newbie in coding

**Comment by Agneese-Saini** [comment]
First of all, post in the thread not as a issue on GitHub.
And about redrex, i don't have the gamemode with me! I don't plan to maintain or develop it too, so sorry. Thats the biggest reason why i gave Someone else the gamemode to maintain (i forgot his name).
