### ISSUE TITLE
Disappearing Dialogs

### ISSUE THREAD

**Issue by eoussama** [Agneese-Saini/SA-MP-Files#11]
Hello,

So upon using the latest version of this include, I encountered a weird problem, when I create a dialog (type DIALOG_STYLE_PREVIEW_MODEL), I make it so that for every listitem I click, the other dialog (type DIALOG_STYLE_PREVIEW_MODEL) displays, the problem is, when it displays, it instantly like after 0.5 second 
disappears and the dialog that redirected me to it displays instead,

here is the code snippet.

`
case DIALOG_CAMPTENT_CRAFTING_INDEX :
		{
			if(!response) return ApplyAnimation(playerid, "CAMERA", "camcrch_to_camstnd", 5, 0, 0, 0, 0, 1000, 1);

			switch(listitem)
			{
				case 0: ShowPlayerDialog(playerid, DIALOG_CAMPTENT_CRAFTING_WEAPONS, DIALOG_STYLE_PREVIEW_MODEL, "Camptent - Crafting Menu - Weapons", "\
					336\tBaseball Bat~n~x2 Log of Wood\n\
					335\tKnife~n~x1 Rubber~n~x1 Steel\n\
					337\tShovel~n~x2 Log of Wood~n~x1 Steel\n\
					338\tPool Cue~n~x2 Log of wood", "Select", "Cancel");
				case 1: ShowPlayerDialog(playerid, DIALOG_CAMPTENT_CRAFTING_EQUIPMENT, DIALOG_STYLE_PREVIEW_MODEL, "Camptent - Crafting Menu - Equipment", "\
					19088\tRope~n~x1 Cloth\n\
					18632\tFishing Rod~n~x1 Rope~n~x1 Rubber~n~x1 Steel\n\
					19904\tHeat Vest~n~x1 Rubber~n~x5 Cloth", "Select", "Cancel");
				case 2: ShowPlayerDialog(playerid, DIALOG_CAMPTENT_CRAFTING_MEDICINE, DIALOG_STYLE_PREVIEW_MODEL, "Camptent - Crafting Menu - Medicine", "\
					11747\tBandage~n~x2 Cloth\n\
					2709\tPainkiller~n~x1 Clove~n~x1 Neem\n\
					19570\tAntibiotics~n~x1 Guava~n~x1 Garlic", "Select", "Cancel");
				case 3:
				{

				}
			}
		}

		case DIALOG_CAMPTENT_CRAFTING_WEAPONS :
		{
			if(!response) ShowPlayerDialog(playerid, DIALOG_CAMPTENT_CRAFTING_INDEX, DIALOG_STYLE_PREVIEW_MODEL, "Camptent - Crafting Menu", "346\tWeapons\n2045\tEquipment\n2709\tMedicine\n3383\tCrafting Bench", "Select", "Cancel");
		}

		case DIALOG_CAMPTENT_CRAFTING_EQUIPMENT :
		{
			if(!response) ShowPlayerDialog(playerid, DIALOG_CAMPTENT_CRAFTING_INDEX, DIALOG_STYLE_PREVIEW_MODEL, "Camptent - Crafting Menu", "346\tWeapons\n2045\tEquipment\n2709\tMedicine\n3383\tCrafting Bench", "Select", "Cancel");
		}

		case DIALOG_CAMPTENT_CRAFTING_MEDICINE :
		{
			if(!response) ShowPlayerDialog(playerid, DIALOG_CAMPTENT_CRAFTING_INDEX, DIALOG_STYLE_PREVIEW_MODEL, "Camptent - Crafting Menu", "346\tWeapons\n2045\tEquipment\n2709\tMedicine\n3383\tCrafting Bench", "Select", "Cancel");
		}

`

Note: I never encountered this problem when I used the earlier version.

**Comment by Agneese-Saini** [comment]
Is this still an issue after latest version?
