### ISSUE TITLE
MAX_DIALOG_LIST_ITEMS 

### ISSUE THREAD

**Issue by madarsk** [Agneese-Saini/SA-MP-Files#16]
I wanted to have a dialog menu, where I can choose every possible SA:MP skin (312 in total), but the maximum dialog can show is 256. Can I redefine this limit? Will it cause any problems?

**Comment by IstuntmanI** [comment]
You can safely increase/decrease that limit. It is used just to create arrays to store items in them.

It would be nice to have something like this in the include:
```pawn
#if !defined MAX_DIALOG_LIST_ITEMS
    #define MAX_DIALOG_LIST_ITEMS 256
#endif
```
instead of this:
```pawn
enum
{
    MAX_DIALOG_LIST_ITEMS = 256
};
```

**Comment by Agneese-Saini** [comment]
I changed it in the new update. Now you can predefine those constants before inclusion.
