### ISSUE TITLE
GangZone ID 0

### ISSUE THREAD

**Issue by realhus** [Agneese-Saini/SA-MP-Files#19]
gangzones.inc - GangZone ID 0 always show the default color

**Comment by Agneese-Saini** [comment]
Does other gangzone functions work on id 0? Like Show/Hide/Flash?

**Comment by realhus** [comment]
Other functions work fine. I can show/hide/flash . But it always show the wrong color. Others zones work perfectly the problem is just with the first zone created

**Comment by Agneese-Saini** [comment]
That is so weird, the code is not complex to not be able to read the problem. I guess i have to debug the creating of zones and then showing which might take some time, i'll get back to you when i am done debugging.

**Comment by realhus** [comment]
I tried reproduce the problem using a separate filter-script, this time GangZone ID0 didnt show at all
When I type /test1, then /test2, i see zones id 1 2 3 4 ,but not 0


`#include <a_samp>
#include zcmd
#include gangzones


new Zones[5];

CMD:test1(playerid)
{
	Zones[0]=GangZoneCreate(-901.10,2221.80,-592.00,2571.90);
	Zones[1]=GangZoneCreate(-2324.90,-2584.20,-1964.20,-2212.10);
	Zones[2]=GangZoneCreate(-2646.40,-355.40,-2270.00,-222.50);
	Zones[3]=GangZoneCreate(-2324.90,-2584.20,-1964.20,-2212.10);
	Zones[4]=GangZoneCreate(-2831.80,-430.20,-2646.40,-222.50);

	return 1;
}
CMD:test2(playerid)
{
	GangZoneShowForPlayer(playerid,Zones[0],0x0495CDCC);
	GangZoneShowForPlayer(playerid,Zones[1],0x0495CDCC);
	GangZoneShowForPlayer(playerid,Zones[2],0x0495CDCC);
	GangZoneShowForPlayer(playerid,Zones[3],0x0495CDCC);
	GangZoneShowForPlayer(playerid,Zones[4],0x0495CDCC);
	return 1;
}
`
