### ISSUE TITLE
Progress2

### ISSUE THREAD

**Issue by F96fedebike** [Agneese-Saini/SA-MP-Files#20]
Hi, I've see this thread: http://forum.sa-mp.com/showthread.php?t=629401

You have write this:

> The include also support previous version (1.0 and 2.0) syntax and function names. 

I'll try your include and is not present none of the written functions, especially that for global bars.
Why?

**Comment by Agneese-Saini** [comment]
Hey, sorry for late reply.
So i am planning on restoring the old version which supports old syntax with some internal changes and probably new design for progress bars. Expect a thread on forums includes section soon.
