### ISSUE TITLE
Clarification on weapon_damage.inc

### ISSUE THREAD

**Issue by Chaprnks** [Agneese-Saini/SA-MP-Files#22]
I've noticed that alot of very useful scripts come & go on this repository, but unfortunately there's not much of an announcement when this ever happens. What's even more suprising, is it's not even listed on the repositories README.md

Since hitreg.inc is supposedly abandoned/removed from the repository, is weapon_damage supposed to be the new version of it or something?

Also, it looks strikingly similar to weapon-config, so it makes me wonder; do I need to implement SKY plugin as well? Since weapon-config was abandoned long ago, with some nasty bugs hidden.. this new mysterious weapon_damage just might be my perfect solution :D

Thanks again for all your hard work, cracking out code Gammix!

**Comment by Chaprnks** [comment]
I was also curious about EnterExit.pwn. I was about to implement this, but unfortunately textanims.inc has dissapeared, & it's predecessor fader.inc doesn't have any similar/compatible functions to port it into the new include.

**Comment by Agneese-Saini** [comment]
I have been very lazy in maintaining this whole repo!

To answer your questions, yes weapon_damage.inc is kinda newer version of hitreg.inc, but it's not tested at all, i just coded it one day and it would be great if someone can beta test it and report bugs!
EnterExit.pwn, i'll fix it soon with fader.inc implementation! 
And also i have to update Readme.md heavily too :(

**Comment by Chaprnks** [comment]
Excellent! I'll test out the weapon_damage for you & report any bugs I encounter. If you want, I can convert the EnterExit functions to fader.inc & do a push/merge request :)

**Comment by Agneese-Saini** [comment]
Thanks, i already updated EnterExit though! I am working on updating Readm.md now!

**Comment by Chaprnks** [comment]
Having an odd issue with EnterExit, everything seems to be working fine, except the teleport. I walk up to the pickup & all around it, but no fade & no teleport.

**Comment by Agneese-Saini** [comment]
Should be fixed now! I did not converted it to streamer fully, before updating github!

**Comment by Chaprnks** [comment]
You forgot one, line 66 ;)

**Comment by Chaprnks** [comment]
Now it seems to be almost bug free! Pickup, teleport & fading works great, but I can't seem to get out of the interior. There's no visible pickup in the interior also (if there should be one)

**Comment by Agneese-Saini** [comment]
You have to create another EnterExit for inside.

**Comment by Chaprnks** [comment]
Okay, but don't you think it'd be much more efficient & simple to just add the exit functionality along with the entrance?

**Comment by Agneese-Saini** [comment]
It will make the enter exit array very lengthy, hard to read, in my opinion.

All you need to do for now is add another line for interior.

**Comment by Chaprnks** [comment]
The issue I have with doing it that way, is it puts me in an infinite loop of enter/exit

**Comment by Agneese-Saini** [comment]
Well don't make the exit pickup at the same spot of enterance teleport!

**Comment by Chaprnks** [comment]
Wow I feel like a **complete** idiot!

Anyways, do you think you can add RemovePlayerBuilding support for map_loader?

**Comment by Agneese-Saini** [comment]
Yes, i was gonna do that. Anyway, you know how it works? because i didn't provide any info on how it works!

**Comment by Chaprnks** [comment]
Yeah, I can get the jist of it from the code. Basically just input map_parse(const path[]); to the selected map. Although, without RemoveBuildingForPlayer, its basically useless for me =/

(Got like 152 maps in my script right now, fortunately its modulized in separate .pwn's in a folder.. but all those hooks are starting to cause issues with the script. Not to mention the added compile time)

**Comment by Agneese-Saini** [comment]
There you go! I added RemoveBuildingForPlayer in parser. Try it out, i haven't tested anything!

**Comment by Chaprnks** [comment]
Awesome, thanks! Finally found a perfect solution. Tried so many in the recent years (SSMM was way too complex & the editor program it came with kept crashing. the ADM or something one by the guy who makes 3dtryg include also was too complicated, cause it basically just compiled each map into its own filterscript, leaving me with hundreds of filterscripts on a single server.cfg)

**Comment by Agneese-Saini** [comment]
Alright, so you wanna close this issue, if you got your solution (i don't like open issues)!

Also checkout the README.md, i just updated it and also cleaned the Repo, removed some useless codes!
