### ISSUE TITLE
Question regarding map_parser.inc

### ISSUE THREAD

**Issue by Chaprnks** [Agneese-Saini/SA-MP-Files#24]
I loaded all my maps (76 to test) & the console even said the maps loaded correctly.. but nothing is shown ingame, no RemoveBuilding nor CreateDynamicObject

**Comment by Agneese-Saini** [comment]
I didn't tested the map_parser so i was expecting bugs! I will do testing soon, could you send me an example map file i could use for testing.

**Comment by Chaprnks** [comment]
![uvoxg6f](https://user-images.githubusercontent.com/6340970/44004672-332a7e6c-9e34-11e8-941d-f911707bfc43.png)

**Comment by Chaprnks** [comment]
This also bugs up with multiple SetDynamicObjectMaterial's on one CreateDynamicObject

**Comment by Agneese-Saini** [comment]
Map parser is unstable and requires lot of work, and i don't have time for it, sorry.

map_parser.inc has been deleted from repo.
