### ISSUE TITLE
Targetid

### ISSUE THREAD

**Issue by Darkeen** [Agneese-Saini/SA-MP-Files#25]
OnPlayerStateChange > newstate == PLAYER_STATE_ONFOOT > SpectatePlayer(**playerid**, playerid, SPECTATE_MODE_NORMAL);

First"playerid" should be "i".
Line: 713

![img](https://user-images.githubusercontent.com/8920778/45725541-b2402380-bb91-11e8-8f34-865cbdfca546.png)

BTW, thanks for the fs.

**Comment by Agneese-Saini** [comment]
You could've made a Pull Request for this kind of problem/fix.

Anyways, thanks for reporting, it has been fixed 👍
