### ISSUE TITLE
map_parse bug

### ISSUE THREAD

**Issue by ghost** [Agneese-Saini/SA-MP-Files#26]
new tmpobjid;
tmpobjid = CreateDynamicObject(19789, 665.249450, 2497.190673, 1279.320312, 0.000000, -0.199999, 33.600017, -1, -1, -1, 300.00, 300.00); 
SetDynamicObjectMaterial(tmpobjid, 0, 18646, "matcolours", "grey-10-percent", 0x00000000);
tmpobjid = CreateDynamicObject(19789, 665.246520, 2497.188964, 1280.280395, 0.000000, -0.199999, 33.600017, -1, -1, -1, 300.00, 300.00); 
SetDynamicObjectMaterial(tmpobjid, 0, 18646, "matcolours", "grey-10-percent", 0x00000000);
If i have objects in this format include not reads them. This is particularly burdensome because in such a format there are objects from texture studio. Here https://github.com/Southclaws/samp-object-loader/blob/master/object-loader.pwn it is working good

**Comment by Agneese-Saini** [comment]
Map parser was in ALPHA and i don't have time to update/fix it, sorry.
