### ISSUE TITLE
Stop this mono repository mess! (Issue about bad habits in Git)

### ISSUE THREAD

**Issue by BigETI** [Agneese-Saini/SA-MP-Files#29]
# Issues
Many people do follow the progress of your releases, and so far nothing much has changed regarding the issues mentioned by community members.
This repository is an example of using Git and GitHub in an incorrect way.
For example:
- It is a mono repository for multiple independent projects
- Treated as a file uploading service instead of a version control system
- No support for [sampctl](https://github.com/Southclaws/sampctl), as this is a repository for PAWN scripts

# How to solve
## Mono repository
Make a repository for each projects. The benefits for that is that you can properly version your projects independently by using Git tags.
It is more appealing for users and fellow developers to look into your project to contribute or get the needed files from.
GitHub allows developers to make wikis for their projects. This is the one of the best ways to document your code.
You can optimize search engines by naming your repositories according to your releases. This will help users and developers to find your projects easier.
Abadoned projects (refering to https://github.com/Agneese-Saini/SA-MP/issues/27) do not have to be removed, and encourage developers to update your stuff.

## File uploading
GitHub is not designed to be a file uploading service. It uses Git to be a platform with version control in mind for open-source and closed-source projects.
I encourage you to use the official Git client for all of your projects, leaving the file uploading feature of GitHub in case of an emergency where you can't for some reason use a Git client.

## Using sampctl
I can't tell you enough to use [sampctl](https://github.com/Southclaws/sampctl) for your projects. It is well documented and straight forward to use. It is farly easy to implement sampctl into your projects. You don't need a master degree in computer science to work with sampctl.
If you use sampctl, you don't have to redirect users to download the required dependecies. sampctl automates that very process.

# Conclusion
I hope you won't come up with an excuse to ignore the advices given to you.

**Comment by 0x416c69** [comment]
sampctl for n00bs
Edit: Ah shit, here we go again (burger gang jumping on thumbs down)

**Comment by Bronzal** [comment]
sampctl for double n00bs
