### ISSUE TITLE
gmenu.inc - New bug detected

### ISSUE THREAD

**Issue by Zorono** [Agneese-Saini/SA-MP-Files#3]
hello dude.

i found a new bug on gmenu include yesterday and i emailed you it on skype. 
and its -> on scrolling bettwen ittems on my menus it always return my non-respone message --> 'order canceled' please fix that bug soon sir
i mean on switching between my items on my menus and betwen my menus it always returns both of my non-respone message -> 'Order Canceled' & respone codes 'you have just bought this weapon for .....$' please fix this bug soon sir.....

**Comment by Agneese-Saini** [comment]
Hey sorry for late reply. But i couldn't get the problem. 
Is it a response related issue; related to "OnMenuResponse" values?

**Comment by Zorono** [comment]
it might be related to the 'OnMenuRespone' **_Values_**.

**Comment by Agneese-Saini** [comment]
Ok, can you give me a sample code you use to interact with gmenus. So that i can test on my machine and see if the issue still exists. It will help me find out the problem.

**Comment by Zorono** [comment]
sent you it on skype - sorry but its private code

**Comment by Zorono** [comment]
waiting for any kind of replies or **_bug fixs_**.....

**Comment by Agneese-Saini** [comment]
Sorry, i am pretty busy in real life. I just made an update for dialogs. This will be next.

**Comment by Agneese-Saini** [comment]
All the bugs should be fixed in the new version. 
Thanks
