### ISSUE TITLE
fader.inc

### ISSUE THREAD

**Issue by samp-pinch** [Agneese-Saini/SA-MP-Files#35]
I just want to say some things because I started creating my own fader include and I cannot waste any more time on this because I almost rewritten 70% of the code and still some things weren't good.

So here is the thing:
You're increasing `idx` with counter++ variable but you do not increase the actuall variable so problem and infinite loop appears in looping thorugh them.

I also noticed that Internal_StopFade wasn't even called and some functions like Valid variable weren't true so PlayerTextDrawStopFade never worked.
( Do not get me wrong, it WAS called only when fading finished but user cannot terminate it with PlayerTextDrawStopFade ).

Also, you missed one argument, it should be `"iiii"` instead of `"iii"` for SetTimer inside PlayerFader.

I recommend you to force users to use foreach if they want to use fader because you won't get anywhere like this :)

**Comment by Agneese-Saini** [comment]
I made a rework of the include but i don't have GTA installed, so i cant really test it. 

Maybe you can give it a shot, that be great.

**Comment by tr1xy** [comment]
@Agneese-Saini sure (this is my new git) 👍
