### ISSUE TITLE
Progress2

### ISSUE THREAD

**Issue by OrdeneauxBiggar377** [Agneese-Saini/SA-MP-Files#4]
Could you add fully support to use your version together with the Editor from Emmet_ ?
I tried to create a Progressbar, but I can only move it to left and right, up and down doesn't work.

Your version is kinda useless if it's not possible to use it together with an editor..

**Comment by Agneese-Saini** [comment]
That bug was fixed a while ago in my SAMP-Files repo.

When i have time, i will modify Emmet's editor or remake one with global and player bar support.
