### ISSUE TITLE
EnterExit.pwn compatibility issue

### ISSUE THREAD

**Issue by Chaprnks** [Agneese-Saini/SA-MP-Files#41]
After trying to test EnterExit.pwn, I realized its using an old version of fader.inc. I tried to update the code for the latest fader.pwn, but it resulted in a bugged entrance. After walking up to the entrance, it fades the screen; but doesn't unfade back (stuck at black screen).

**Comment by Agneese-Saini** [comment]
https://github.com/Agneese-Saini/SA-MP/commit/6b522fed467f22a0af097575c3c454a6abc636a6
