### ISSUE TITLE
fader.inc problem

### ISSUE THREAD

**Issue by h3ckphy** [Agneese-Saini/SA-MP-Files#43]
Hello. I found a disadvantage in your fader.inc. When using with fader_type_text which has outline fader doesn't work correctly. Because it has to change background color too (from 0 to 255). If I turn off outline there's no need to change background and it works properly.
Check the screens (outline is set):
https://imgur.com/a/4cXgnWE

**Comment by h3ckphy** [comment]
There is another bug I've found

**Comment by Agneese-Saini** [comment]
https://github.com/Agneese-Saini/SA-MP/commit/699c6dc442f2896c6d746bd3eb488a8f8563fa55

The new update should fix it.
