### ISSUE TITLE
textanims.inc

### ISSUE THREAD

**Issue by SalikDavince** [Agneese-Saini/SA-MP-Files#46]
In connection with the closure of the forum, I tried to search for your inclusion, but all without success, I would like to see this inclusion "**textanims**", and some other developments as well, I apologize for the English)

**Comment by Agneese-Saini** [comment]
That library doesnt exsist anymore but you can find slightly similar library: https://github.com/Agneese-Saini/SA-MP/blob/master/pawno/include/fader.inc
