### ISSUE TITLE
lagcomp explosion and vehicle minigun damage issue

### ISSUE THREAD

**Issue by AHellerL** [Agneese-Saini/SA-MP-Files#6]
No idea why.

**Comment by AHellerL** [comment]
Check line 541

playerDeath[playerid][E_PLAYER_DEATH_KILLERID] = INVALID_PLAYER_ID; should equal issuerid instead.

**Comment by AHellerL** [comment]
damage wasnt processed onplayertakedamage

**Comment by AHellerL** [comment]
process damage on OnPlayerTakeDamage

**Comment by Agneese-Saini** [comment]
So the player isn't getting hurt from vehicle guns and grenade type of explosions?

**Comment by AHellerL** [comment]
Yea, but the fix which I have provided earlier solves this issue. Tho, please do take a second look at it.
 (deathcall is again not working for those weaponids [I am testing it other way around, will notify if it works out] )

**Comment by Agneese-Saini** [comment]
Did you happen to check the new update?
Let me know what's the output and i'll try to fix bugs if any encountered.

**Comment by AHellerL** [comment]
I actually started experimenting with your include and modified it a little to suit up my needs. (everything works fine with what I did). But I'll test this version and let you know if anything comes up.

My version includes this.
-Hooked (Get) health and armour.
-Hooked OnPlayerStateChange (to change player's team from 655 to his id, when he is inside a vehicle) [using your anti friendly vehicle fire method, in the .amx)
-Fixed Knifing(OnPlayerUpdate is not hooked in the include that i have provided)[again modifyed your anti team knifing method)
-AntiSpawn kill feature(additional)
-Explosions, motolovs, grenades etc are processed under OnPlayerTakeDamage
-DeathDisplay function, this can be used for when you want to set player's killerid from the server. e.g after creating a explosion, you can DeathDisplay(playerid,killerid,reason) and when the player dies, this'll show up. This is also for those who had last shot somebody. (to be optimized)

https://pastebin.com/Uj3ZhV2E

**Comment by Agneese-Saini** [comment]
I am closing this since i dont plan to code anymore for now!
