### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Vince0789** [Agneese-Saini/SA-MP-Files#7]
You ought to add a proper open source license to your code.

https://www.infoworld.com/article/2615869/open-source-software/github-needs-to-take-open-source-seriously.html

_Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such. Any time you're using software you didn't write, licensing should be considered and abided._

**Comment by Agneese-Saini** [comment]
Yeah, i'll add license in a moment. 
Thanks
