### ISSUE TITLE
Hi Gammix !

### ISSUE THREAD

**Issue by stalkeriy2010** [Agneese-Saini/SA-MP-Files#9]
sorry about that !
but i didn't find  anyway to contact you, i have saw your impressive gamemode in samp forums (redrex gamemode) and i can't find any links, i found an older version redrex build 2/3 but there's a problem in saving system it cant save skins etc... to test it so can you please give me a working link to download it and give me permission to edit it, thanks !!!! 

PS: if you can give me the Redrex gamemode V5 that would be greater !

**Comment by Agneese-Saini** [comment]
Check the last few comments you'll find a link there.

**Comment by stalkeriy2010** [comment]
thanks !!!!!!
